// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/grpc/key_provider/key_provider.proto

package key_provider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyProviderKeyWrapProtocolInput struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	KeyProviderKeyWrapProtocolInput []byte                 `protobuf:"bytes,1,opt,name=key_provider_key_wrap_protocol_input,json=keyProviderKeyWrapProtocolInput,proto3" json:"key_provider_key_wrap_protocol_input,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *KeyProviderKeyWrapProtocolInput) Reset() {
	*x = KeyProviderKeyWrapProtocolInput{}
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyProviderKeyWrapProtocolInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyProviderKeyWrapProtocolInput) ProtoMessage() {}

func (x *KeyProviderKeyWrapProtocolInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyProviderKeyWrapProtocolInput.ProtoReflect.Descriptor instead.
func (*KeyProviderKeyWrapProtocolInput) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_key_provider_key_provider_proto_rawDescGZIP(), []int{0}
}

func (x *KeyProviderKeyWrapProtocolInput) GetKeyProviderKeyWrapProtocolInput() []byte {
	if x != nil {
		return x.KeyProviderKeyWrapProtocolInput
	}
	return nil
}

type KeyProviderKeyWrapProtocolOutput struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	KeyProviderKeyWrapProtocolOutput []byte                 `protobuf:"bytes,1,opt,name=key_provider_key_wrap_protocol_output,json=keyProviderKeyWrapProtocolOutput,proto3" json:"key_provider_key_wrap_protocol_output,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *KeyProviderKeyWrapProtocolOutput) Reset() {
	*x = KeyProviderKeyWrapProtocolOutput{}
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyProviderKeyWrapProtocolOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyProviderKeyWrapProtocolOutput) ProtoMessage() {}

func (x *KeyProviderKeyWrapProtocolOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyProviderKeyWrapProtocolOutput.ProtoReflect.Descriptor instead.
func (*KeyProviderKeyWrapProtocolOutput) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_key_provider_key_provider_proto_rawDescGZIP(), []int{1}
}

func (x *KeyProviderKeyWrapProtocolOutput) GetKeyProviderKeyWrapProtocolOutput() []byte {
	if x != nil {
		return x.KeyProviderKeyWrapProtocolOutput
	}
	return nil
}

type KeyProviderGetReportInput struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReportDataHexString string                 `protobuf:"bytes,1,opt,name=report_data_hex_string,json=reportDataHexString,proto3" json:"report_data_hex_string,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *KeyProviderGetReportInput) Reset() {
	*x = KeyProviderGetReportInput{}
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyProviderGetReportInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyProviderGetReportInput) ProtoMessage() {}

func (x *KeyProviderGetReportInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyProviderGetReportInput.ProtoReflect.Descriptor instead.
func (*KeyProviderGetReportInput) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_key_provider_key_provider_proto_rawDescGZIP(), []int{2}
}

func (x *KeyProviderGetReportInput) GetReportDataHexString() string {
	if x != nil {
		return x.ReportDataHexString
	}
	return ""
}

type KeyProviderGetReportOutput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReportHexString string                 `protobuf:"bytes,1,opt,name=report_hex_string,json=reportHexString,proto3" json:"report_hex_string,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KeyProviderGetReportOutput) Reset() {
	*x = KeyProviderGetReportOutput{}
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyProviderGetReportOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyProviderGetReportOutput) ProtoMessage() {}

func (x *KeyProviderGetReportOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyProviderGetReportOutput.ProtoReflect.Descriptor instead.
func (*KeyProviderGetReportOutput) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_key_provider_key_provider_proto_rawDescGZIP(), []int{3}
}

func (x *KeyProviderGetReportOutput) GetReportHexString() string {
	if x != nil {
		return x.ReportHexString
	}
	return ""
}

type KeyProviderGetAttestationDataInput struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	B64RuntimeDataString string                 `protobuf:"bytes,1,opt,name=b64_runtime_data_string,json=b64RuntimeDataString,proto3" json:"b64_runtime_data_string,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *KeyProviderGetAttestationDataInput) Reset() {
	*x = KeyProviderGetAttestationDataInput{}
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyProviderGetAttestationDataInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyProviderGetAttestationDataInput) ProtoMessage() {}

func (x *KeyProviderGetAttestationDataInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyProviderGetAttestationDataInput.ProtoReflect.Descriptor instead.
func (*KeyProviderGetAttestationDataInput) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_key_provider_key_provider_proto_rawDescGZIP(), []int{4}
}

func (x *KeyProviderGetAttestationDataInput) GetB64RuntimeDataString() string {
	if x != nil {
		return x.B64RuntimeDataString
	}
	return ""
}

type KeyProviderGetAttestationDataOutput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EndorsedTcb       string                 `protobuf:"bytes,1,opt,name=endorsed_tcb,json=endorsedTcb,proto3" json:"endorsed_tcb,omitempty"`
	Certs             string                 `protobuf:"bytes,2,opt,name=certs,proto3" json:"certs,omitempty"`
	AttestationReport string                 `protobuf:"bytes,3,opt,name=attestation_report,json=attestationReport,proto3" json:"attestation_report,omitempty"`
	UvmReferenceInfo  string                 `protobuf:"bytes,4,opt,name=uvm_reference_info,json=uvmReferenceInfo,proto3" json:"uvm_reference_info,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KeyProviderGetAttestationDataOutput) Reset() {
	*x = KeyProviderGetAttestationDataOutput{}
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyProviderGetAttestationDataOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyProviderGetAttestationDataOutput) ProtoMessage() {}

func (x *KeyProviderGetAttestationDataOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyProviderGetAttestationDataOutput.ProtoReflect.Descriptor instead.
func (*KeyProviderGetAttestationDataOutput) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_key_provider_key_provider_proto_rawDescGZIP(), []int{5}
}

func (x *KeyProviderGetAttestationDataOutput) GetEndorsedTcb() string {
	if x != nil {
		return x.EndorsedTcb
	}
	return ""
}

func (x *KeyProviderGetAttestationDataOutput) GetCerts() string {
	if x != nil {
		return x.Certs
	}
	return ""
}

func (x *KeyProviderGetAttestationDataOutput) GetAttestationReport() string {
	if x != nil {
		return x.AttestationReport
	}
	return ""
}

func (x *KeyProviderGetAttestationDataOutput) GetUvmReferenceInfo() string {
	if x != nil {
		return x.UvmReferenceInfo
	}
	return ""
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_key_provider_key_provider_proto_rawDescGZIP(), []int{6}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_key_provider_key_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_key_provider_key_provider_proto_rawDescGZIP(), []int{7}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_grpc_key_provider_key_provider_proto protoreflect.FileDescriptor

const file_pkg_grpc_key_provider_key_provider_proto_rawDesc = "" +
	"\n" +
	"(pkg/grpc/key_provider/key_provider.proto\x12\fkey_provider\"p\n" +
	"\x1fKeyProviderKeyWrapProtocolInput\x12M\n" +
	"$key_provider_key_wrap_protocol_input\x18\x01 \x01(\fR\x1fkeyProviderKeyWrapProtocolInput\"s\n" +
	" KeyProviderKeyWrapProtocolOutput\x12O\n" +
	"%key_provider_key_wrap_protocol_output\x18\x01 \x01(\fR keyProviderKeyWrapProtocolOutput\"P\n" +
	"\x19KeyProviderGetReportInput\x123\n" +
	"\x16report_data_hex_string\x18\x01 \x01(\tR\x13reportDataHexString\"H\n" +
	"\x1aKeyProviderGetReportOutput\x12*\n" +
	"\x11report_hex_string\x18\x01 \x01(\tR\x0freportHexString\"[\n" +
	"\"KeyProviderGetAttestationDataInput\x125\n" +
	"\x17b64_runtime_data_string\x18\x01 \x01(\tR\x14b64RuntimeDataString\"\xbb\x01\n" +
	"#KeyProviderGetAttestationDataOutput\x12!\n" +
	"\fendorsed_tcb\x18\x01 \x01(\tR\vendorsedTcb\x12\x14\n" +
	"\x05certs\x18\x02 \x01(\tR\x05certs\x12-\n" +
	"\x12attestation_report\x18\x03 \x01(\tR\x11attestationReport\x12,\n" +
	"\x12uvm_reference_info\x18\x04 \x01(\tR\x10uvmReferenceInfo\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x91\x04\n" +
	"\x12KeyProviderService\x12j\n" +
	"\aWrapKey\x12-.key_provider.KeyProviderKeyWrapProtocolInput\x1a..key_provider.KeyProviderKeyWrapProtocolOutput\"\x00\x12l\n" +
	"\tUnWrapKey\x12-.key_provider.KeyProviderKeyWrapProtocolInput\x1a..key_provider.KeyProviderKeyWrapProtocolOutput\"\x00\x12`\n" +
	"\tGetReport\x12'.key_provider.KeyProviderGetReportInput\x1a(.key_provider.KeyProviderGetReportOutput\"\x00\x12{\n" +
	"\x12GetAttestationData\x120.key_provider.KeyProviderGetAttestationDataInput\x1a1.key_provider.KeyProviderGetAttestationDataOutput\"\x00\x12B\n" +
	"\bSayHello\x12\x1a.key_provider.HelloRequest\x1a\x18.key_provider.HelloReply\"\x00B\x10Z\x0e./key_providerb\x06proto3"

var (
	file_pkg_grpc_key_provider_key_provider_proto_rawDescOnce sync.Once
	file_pkg_grpc_key_provider_key_provider_proto_rawDescData []byte
)

func file_pkg_grpc_key_provider_key_provider_proto_rawDescGZIP() []byte {
	file_pkg_grpc_key_provider_key_provider_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_key_provider_key_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_key_provider_key_provider_proto_rawDesc), len(file_pkg_grpc_key_provider_key_provider_proto_rawDesc)))
	})
	return file_pkg_grpc_key_provider_key_provider_proto_rawDescData
}

var file_pkg_grpc_key_provider_key_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_grpc_key_provider_key_provider_proto_goTypes = []any{
	(*KeyProviderKeyWrapProtocolInput)(nil),     // 0: key_provider.KeyProviderKeyWrapProtocolInput
	(*KeyProviderKeyWrapProtocolOutput)(nil),    // 1: key_provider.KeyProviderKeyWrapProtocolOutput
	(*KeyProviderGetReportInput)(nil),           // 2: key_provider.KeyProviderGetReportInput
	(*KeyProviderGetReportOutput)(nil),          // 3: key_provider.KeyProviderGetReportOutput
	(*KeyProviderGetAttestationDataInput)(nil),  // 4: key_provider.KeyProviderGetAttestationDataInput
	(*KeyProviderGetAttestationDataOutput)(nil), // 5: key_provider.KeyProviderGetAttestationDataOutput
	(*HelloRequest)(nil),                        // 6: key_provider.HelloRequest
	(*HelloReply)(nil),                          // 7: key_provider.HelloReply
}
var file_pkg_grpc_key_provider_key_provider_proto_depIdxs = []int32{
	0, // 0: key_provider.KeyProviderService.WrapKey:input_type -> key_provider.KeyProviderKeyWrapProtocolInput
	0, // 1: key_provider.KeyProviderService.UnWrapKey:input_type -> key_provider.KeyProviderKeyWrapProtocolInput
	2, // 2: key_provider.KeyProviderService.GetReport:input_type -> key_provider.KeyProviderGetReportInput
	4, // 3: key_provider.KeyProviderService.GetAttestationData:input_type -> key_provider.KeyProviderGetAttestationDataInput
	6, // 4: key_provider.KeyProviderService.SayHello:input_type -> key_provider.HelloRequest
	1, // 5: key_provider.KeyProviderService.WrapKey:output_type -> key_provider.KeyProviderKeyWrapProtocolOutput
	1, // 6: key_provider.KeyProviderService.UnWrapKey:output_type -> key_provider.KeyProviderKeyWrapProtocolOutput
	3, // 7: key_provider.KeyProviderService.GetReport:output_type -> key_provider.KeyProviderGetReportOutput
	5, // 8: key_provider.KeyProviderService.GetAttestationData:output_type -> key_provider.KeyProviderGetAttestationDataOutput
	7, // 9: key_provider.KeyProviderService.SayHello:output_type -> key_provider.HelloReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpc_key_provider_key_provider_proto_init() }
func file_pkg_grpc_key_provider_key_provider_proto_init() {
	if File_pkg_grpc_key_provider_key_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_key_provider_key_provider_proto_rawDesc), len(file_pkg_grpc_key_provider_key_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_key_provider_key_provider_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_key_provider_key_provider_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_key_provider_key_provider_proto_msgTypes,
	}.Build()
	File_pkg_grpc_key_provider_key_provider_proto = out.File
	file_pkg_grpc_key_provider_key_provider_proto_goTypes = nil
	file_pkg_grpc_key_provider_key_provider_proto_depIdxs = nil
}
