---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  containers:
    - image: "fishersnpregistry.azurecr.io/hello-world-aks:1.0"
      command:
        - python3
        - main.py
      imagePullPolicy: Always
      name: helloworld
      ports:
        - containerPort: 80
        - containerPort: 443
  runtimeClassName: kata-cc
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld-service
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
