// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keyprovider.proto

package keyprovider

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyProviderKeyWrapProtocolInput struct {
	KeyProviderKeyWrapProtocolInput []byte   `protobuf:"bytes,1,opt,name=KeyProviderKeyWrapProtocolInput,proto3" json:"KeyProviderKeyWrapProtocolInput,omitempty"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *KeyProviderKeyWrapProtocolInput) Reset()         { *m = KeyProviderKeyWrapProtocolInput{} }
func (m *KeyProviderKeyWrapProtocolInput) String() string { return proto.CompactTextString(m) }
func (*KeyProviderKeyWrapProtocolInput) ProtoMessage()    {}
func (*KeyProviderKeyWrapProtocolInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_da74c8e785ad390c, []int{0}
}

func (m *KeyProviderKeyWrapProtocolInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyProviderKeyWrapProtocolInput.Unmarshal(m, b)
}
func (m *KeyProviderKeyWrapProtocolInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyProviderKeyWrapProtocolInput.Marshal(b, m, deterministic)
}
func (m *KeyProviderKeyWrapProtocolInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyProviderKeyWrapProtocolInput.Merge(m, src)
}
func (m *KeyProviderKeyWrapProtocolInput) XXX_Size() int {
	return xxx_messageInfo_KeyProviderKeyWrapProtocolInput.Size(m)
}
func (m *KeyProviderKeyWrapProtocolInput) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyProviderKeyWrapProtocolInput.DiscardUnknown(m)
}

var xxx_messageInfo_KeyProviderKeyWrapProtocolInput proto.InternalMessageInfo

func (m *KeyProviderKeyWrapProtocolInput) GetKeyProviderKeyWrapProtocolInput() []byte {
	if m != nil {
		return m.KeyProviderKeyWrapProtocolInput
	}
	return nil
}

type KeyProviderKeyWrapProtocolOutput struct {
	KeyProviderKeyWrapProtocolOutput []byte   `protobuf:"bytes,1,opt,name=KeyProviderKeyWrapProtocolOutput,proto3" json:"KeyProviderKeyWrapProtocolOutput,omitempty"`
	XXX_NoUnkeyedLiteral             struct{} `json:"-"`
	XXX_unrecognized                 []byte   `json:"-"`
	XXX_sizecache                    int32    `json:"-"`
}

func (m *KeyProviderKeyWrapProtocolOutput) Reset()         { *m = KeyProviderKeyWrapProtocolOutput{} }
func (m *KeyProviderKeyWrapProtocolOutput) String() string { return proto.CompactTextString(m) }
func (*KeyProviderKeyWrapProtocolOutput) ProtoMessage()    {}
func (*KeyProviderKeyWrapProtocolOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_da74c8e785ad390c, []int{1}
}

func (m *KeyProviderKeyWrapProtocolOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyProviderKeyWrapProtocolOutput.Unmarshal(m, b)
}
func (m *KeyProviderKeyWrapProtocolOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyProviderKeyWrapProtocolOutput.Marshal(b, m, deterministic)
}
func (m *KeyProviderKeyWrapProtocolOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyProviderKeyWrapProtocolOutput.Merge(m, src)
}
func (m *KeyProviderKeyWrapProtocolOutput) XXX_Size() int {
	return xxx_messageInfo_KeyProviderKeyWrapProtocolOutput.Size(m)
}
func (m *KeyProviderKeyWrapProtocolOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyProviderKeyWrapProtocolOutput.DiscardUnknown(m)
}

var xxx_messageInfo_KeyProviderKeyWrapProtocolOutput proto.InternalMessageInfo

func (m *KeyProviderKeyWrapProtocolOutput) GetKeyProviderKeyWrapProtocolOutput() []byte {
	if m != nil {
		return m.KeyProviderKeyWrapProtocolOutput
	}
	return nil
}

type KeyProviderGetReportInput struct {
	ReportDataHexString  string   `protobuf:"bytes,1,opt,name=reportDataHexString,proto3" json:"reportDataHexString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyProviderGetReportInput) Reset()         { *m = KeyProviderGetReportInput{} }
func (m *KeyProviderGetReportInput) String() string { return proto.CompactTextString(m) }
func (*KeyProviderGetReportInput) ProtoMessage()    {}
func (*KeyProviderGetReportInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_da74c8e785ad390c, []int{2}
}

func (m *KeyProviderGetReportInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyProviderGetReportInput.Unmarshal(m, b)
}
func (m *KeyProviderGetReportInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyProviderGetReportInput.Marshal(b, m, deterministic)
}
func (m *KeyProviderGetReportInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyProviderGetReportInput.Merge(m, src)
}
func (m *KeyProviderGetReportInput) XXX_Size() int {
	return xxx_messageInfo_KeyProviderGetReportInput.Size(m)
}
func (m *KeyProviderGetReportInput) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyProviderGetReportInput.DiscardUnknown(m)
}

var xxx_messageInfo_KeyProviderGetReportInput proto.InternalMessageInfo

func (m *KeyProviderGetReportInput) GetReportDataHexString() string {
	if m != nil {
		return m.ReportDataHexString
	}
	return ""
}

type KeyProviderGetReportOutput struct {
	ReportHexString      string   `protobuf:"bytes,1,opt,name=reportHexString,proto3" json:"reportHexString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyProviderGetReportOutput) Reset()         { *m = KeyProviderGetReportOutput{} }
func (m *KeyProviderGetReportOutput) String() string { return proto.CompactTextString(m) }
func (*KeyProviderGetReportOutput) ProtoMessage()    {}
func (*KeyProviderGetReportOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_da74c8e785ad390c, []int{3}
}

func (m *KeyProviderGetReportOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyProviderGetReportOutput.Unmarshal(m, b)
}
func (m *KeyProviderGetReportOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyProviderGetReportOutput.Marshal(b, m, deterministic)
}
func (m *KeyProviderGetReportOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyProviderGetReportOutput.Merge(m, src)
}
func (m *KeyProviderGetReportOutput) XXX_Size() int {
	return xxx_messageInfo_KeyProviderGetReportOutput.Size(m)
}
func (m *KeyProviderGetReportOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyProviderGetReportOutput.DiscardUnknown(m)
}

var xxx_messageInfo_KeyProviderGetReportOutput proto.InternalMessageInfo

func (m *KeyProviderGetReportOutput) GetReportHexString() string {
	if m != nil {
		return m.ReportHexString
	}
	return ""
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da74c8e785ad390c, []int{4}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_da74c8e785ad390c, []int{5}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*KeyProviderKeyWrapProtocolInput)(nil), "keyprovider.keyProviderKeyWrapProtocolInput")
	proto.RegisterType((*KeyProviderKeyWrapProtocolOutput)(nil), "keyprovider.keyProviderKeyWrapProtocolOutput")
	proto.RegisterType((*KeyProviderGetReportInput)(nil), "keyprovider.keyProviderGetReportInput")
	proto.RegisterType((*KeyProviderGetReportOutput)(nil), "keyprovider.keyProviderGetReportOutput")
	proto.RegisterType((*HelloRequest)(nil), "keyprovider.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "keyprovider.HelloReply")
}

func init() { proto.RegisterFile("keyprovider.proto", fileDescriptor_da74c8e785ad390c) }

var fileDescriptor_da74c8e785ad390c = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x21, 0x1a, 0x91, 0x11, 0x43, 0x5c, 0x0f, 0x42, 0x2f, 0x90, 0x3d, 0x20, 0x07, 0x45,
	0xa3, 0x2f, 0x60, 0x8c, 0x51, 0xb4, 0x31, 0x92, 0x12, 0x63, 0xe2, 0xc1, 0x64, 0xc5, 0x09, 0xd6,
	0x96, 0xee, 0xba, 0xdd, 0x12, 0xf7, 0x1d, 0x7c, 0x68, 0xd3, 0xb2, 0x90, 0x85, 0x14, 0xeb, 0xc9,
	0x5b, 0x67, 0xe7, 0x9b, 0xff, 0x6f, 0xff, 0xe9, 0xc2, 0x5e, 0x80, 0x5a, 0x48, 0x3e, 0xf5, 0xdf,
	0x50, 0xf6, 0x84, 0xe4, 0x8a, 0x93, 0x1d, 0xeb, 0x88, 0x06, 0xd0, 0x0a, 0x50, 0x0f, 0x4c, 0xe9,
	0xa2, 0x7e, 0x92, 0x4c, 0x0c, 0x52, 0x6e, 0xc4, 0xc3, 0xdb, 0x48, 0x24, 0x8a, 0xf4, 0xa1, 0xe5,
	0xfe, 0x8e, 0x34, 0xca, 0xed, 0x72, 0xb7, 0xe6, 0x15, 0x61, 0x34, 0x82, 0xf6, 0x7a, 0xb3, 0x87,
	0x44, 0xa5, 0x6e, 0x77, 0xd0, 0x76, 0x0b, 0x18, 0x63, 0x57, 0xc8, 0xd1, 0x7b, 0x68, 0x5a, 0x7e,
	0x37, 0xa8, 0x3c, 0x14, 0x5c, 0xaa, 0xd9, 0x67, 0x9d, 0xc2, 0xbe, 0xcc, 0xca, 0x2b, 0xa6, 0x58,
	0x1f, 0xbf, 0x86, 0x4a, 0xfa, 0xd1, 0x38, 0xd3, 0xae, 0x7a, 0x79, 0x2d, 0x7a, 0x0d, 0x4e, 0x9e,
	0x9c, 0x79, 0xf1, 0x2e, 0xd4, 0x67, 0x43, 0xab, 0x5a, 0xab, 0xc7, 0x94, 0x42, 0xad, 0x8f, 0x61,
	0xc8, 0x3d, 0xfc, 0x4c, 0x30, 0x56, 0x84, 0xc0, 0x66, 0xc4, 0x26, 0x68, 0xf0, 0xec, 0x99, 0x76,
	0x00, 0x0c, 0x23, 0x42, 0x4d, 0x1a, 0x50, 0x99, 0x60, 0x1c, 0xb3, 0xf1, 0x1c, 0x9a, 0x97, 0x67,
	0xdf, 0x1b, 0x40, 0xac, 0x1c, 0x86, 0x28, 0xa7, 0xfe, 0x08, 0xc9, 0x3b, 0x54, 0xd2, 0x3c, 0x5c,
	0xd4, 0xe4, 0xa8, 0x67, 0xff, 0x02, 0x05, 0xcb, 0x76, 0x8e, 0xff, 0x48, 0x9b, 0x84, 0x4b, 0xe4,
	0x03, 0xaa, 0x8f, 0xd1, 0x3f, 0x79, 0xbd, 0x40, 0x75, 0x91, 0x3a, 0xe9, 0xac, 0x9b, 0x5e, 0xde,
	0xb3, 0x73, 0x58, 0xc8, 0x2d, 0xf4, 0x2f, 0x60, 0x7b, 0xc8, 0x74, 0x96, 0x3b, 0x69, 0x2e, 0x8d,
	0xd9, 0xfb, 0x72, 0x0e, 0xf2, 0x5a, 0x22, 0xd4, 0xb4, 0x74, 0x59, 0x7f, 0xde, 0xed, 0x9d, 0x58,
	0xdd, 0xd7, 0xad, 0xec, 0xce, 0x9d, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x86, 0x0a, 0x5b, 0x0b,
	0x88, 0x03, 0x00, 0x00,
}
