FROM alpine:3.17.1

RUN apk update && apk add --no-cache cryptsetup fuse curl

COPY ./bin/azmount ./bin/remotefs ./bin/get-snp-report /bin/
COPY encfs.sh /

RUN chmod +x /*.sh; date > /made-date
