FROM mcr.microsoft.com/cbl-mariner/base/core:2.0

RUN tdnf update -y && tdnf upgrade -y && tdnf install wget curl jq tar ca-certificates vim openssh-server -y && tdnf clean all

# clearly this is extremely insecure but is only for debugging
# do not copy this.
RUN useradd --uid 1000 --gid 0 --non-unique -ms /bin/bash auserwithalongname
RUN echo "auserwithalongname:shortpassword" | chpasswd
RUN mkdir /run/sshd

# set the start command which will be used by default by ACI
# note that this script exposes attestation on an external port
# NEVER DO THIS IN PRODUCTION as it exposes the attestations
# which can be used to trick an attestation agent or relying party

COPY ./bin/skr ./bin/get-snp-report ./bin/verbose-report /bin/
COPY ./docker/skr/skr.sh ./docker/skr/skr-debug.sh ./docker/skr/tests/*_client.sh ./docker/skr/tests/skr_test.sh /
RUN mkdir -p /tests/skr; mv *_client.sh /tests/skr; mv skr_test.sh /tests/skr
RUN chmod +x /*.sh /tests/skr/*.sh; date > /made-date

# set the start command
CMD [ "sleep", "1000000" ]
