FROM mcr.microsoft.com/devcontainers/go:dev-1.24-bookworm AS build
ENV PROJECT_DIR=/go/src/github.com/microsoft
WORKDIR ${PROJECT_DIR}/confidential-sidecar-containers
COPY . ./
RUN cd tools/get-snp-report && make && mv bin/get-snp-report / && mv bin/get-fake-snp-report /

RUN cd cmd/skr && CGO_ENABLED=0 GOOS=linux go build -o /skr -ldflags="-s -w" main.go

FROM mcr.microsoft.com/azurelinux/base/core:3.0

RUN tdnf update -y && tdnf upgrade -y && tdnf install -y curl ca-certificates && tdnf clean all

COPY --from=build /skr /get-snp-report /get-fake-snp-report ./bin/

ENV BUILD_DIR=/go/src/github.com/microsoft/confidential-sidecar-containers
COPY --from=build ${BUILD_DIR}/docker/skr/skr.sh /
COPY --from=build ${BUILD_DIR}/docker/skr/tests/*_client.sh ${BUILD_DIR}/docker/skr/tests/skr_test.sh /tests/skr/

RUN chmod +x /*.sh /tests/skr/*.sh

# set the start command
CMD [ "/skr.sh" ]
