FROM mcr.microsoft.com/cbl-mariner/base/core:2.0

RUN tdnf update -y && tdnf upgrade -y && tdnf install wget curl jq tar ca-certificates -y && tdnf clean all

COPY ./examples/skr/aks-kata-cc/unwrap.sh /bin/
COPY ./examples/skr/aks-kata-cc/wrapped /
RUN wget -q https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_x86_64.tar.gz &&\
        tar xfz grpcurl_1.8.7_linux_x86_64.tar.gz &&\
        chmod +x grpcurl &&\
        cp grpcurl /bin/ &&\
        rm -f grpcurl*

# set the start command
CMD [ "/bin/sh", "-c", "/bin/unwrap.sh /wrapped /plaintext && cat /plaintext && sleep infinity" ]