ARG GOLANG_VERSION=1.19

FROM mcr.microsoft.com/devcontainers/go:${GOLANG_VERSION} AS build
ENV PROJECT_DIR=/go/src/github.com/microsoft
WORKDIR ${PROJECT_DIR}/confidential-sidecar-containers
COPY . ./
RUN cd tools/get-snp-report && make && mv bin/get-snp-report / && mv bin/get-fake-snp-report /

RUN cd cmd/skr && CGO_ENABLED=0 GOOS=linux go build -o /skr -ldflags="-s -w" main.go

FROM mcr.microsoft.com/cbl-mariner/distroless/minimal:2.0

COPY --from=build /skr /get-snp-report /get-fake-snp-report ./bin/

ENV BUILD_DIR=/go/src/github.com/microsoft/confidential-sidecar-containers
COPY --from=build ${BUILD_DIR}/docker/skr/skr.sh /

# set the start command
CMD [ "/skr.sh" ]
