FROM mcr.microsoft.com/oss/go/microsoft/golang:1.19-fips-cbl-mariner2.0 AS builder-app
WORKDIR /usr/src/app
COPY go.mod cmd/attestation-container .
RUN CGO_ENABLED=0 go build -v -o /usr/local/bin/app ./cmd/attestation-container/
CMD ["app"]
