name: Test Attestation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/push_attestation_image.yml
      - cmd/attestation-container/**
      - docker/attestation-container/**
      - pkg/attest
      - pkg/common
      - vendor/**
      - internal/**

  push:
    branches:
      - main
    paths:
      - .github/workflows/push_attestation_image.yml
      - cmd/attestation-container/**
      - docker/attestation-container/**
      - pkg/attest
      - pkg/common
      - vendor/**
      - internal/**

jobs:
  test-attestation:
    name: Test Attestation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MANAGED_ID_CLIENT_ID }}
          tenant-id: ${{ secrets.MANAGED_ID_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Install c_aci_testing package
        run: ./tests/scripts/install-c-aci-testing.sh

      - name: Test Attestation
        run: python -m unittest discover -s tests/attestation
