apiVersion: v1
kind: Pod
metadata:
 name: skr-secret-provisioning
 labels:
    azure.workload.identity/use: "true"
spec:
  runtimeClassName: kata-cc
  serviceAccountName: $SERVICE_ACCOUNT_NAME
  containers:
  - image: $SKR_IMAGE
    imagePullPolicy: Always
    name: skr
    command:
    - /skr.sh
    env:
    - name: SkrSideCarArgs
      value: ewogICAgImNlcnRjYWNoZSI6IHsKCQkiZW5kcG9pbnRfdHlwZSI6ICJMb2NhbFRISU0iLAoJCSJlbmRwb2ludCI6ICIxNjkuMjU0LjE2OS4yNTQvbWV0YWRhdGEvVEhJTS9hbWQvY2VydGlmaWNhdGlvbiIKCX0gIAp9
    - name: UVM_SECURITY_CONTEXT_DIR
      value: /opt/confidential-containers/share/kata-containers
    - name: Port
      value: "50000"
    - name: ServerType
      value: "grpc"
    volumeMounts:
    - mountPath: /opt/confidential-containers/share/kata-containers/reference-info-base64
      name: endorsement-location
  - image: $EXAMPLE_UNWRAP_IMAGE
    imagePullPolicy: Always
    name: example-unwrap
    command:
      - /bin/sh
      - "-c"
    args:
      - until netstat -anpe | grep 50000; do sleep 3; done; /bin/unwrap.sh /wrapped /plaintext && cat /plaintext && sleep infinity
  imagePullSecrets:
    - name: $ACR_SECRET
  volumes:
    - name: endorsement-location
      hostPath:
        path: /opt/confidential-containers/share/kata-containers/reference-info-base64